apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: policy-member-binding
spec:
  member: serviceAccount:websocket-server@hombrew-iot.iam.gserviceaccount.com
  role: roles/pubsub.subscriber
  resourceRef:
    kind: Project
    name: hombrew-iot
