name: Deploy Websocket Server

on:
  push:
    paths:
      - 'websocket-server/**'
      - '.github/workflows/deploy-websocket-server.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: actions-hub/gcloud@278.0.0
      env:
        PROJECT_ID: ${{secrets.GOOGLE_PROJECT_ID}}
        APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      with:
        args: app deploy
