name: Deploy unix-epoch-gmt

on:
  push:
    paths:
    - 'unix-epoch/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: actions-hub/gcloud@278.0.0
      env:
        PROJECT_ID: ${{secrets.GOOGLE_PROJECT_ID}}
        APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      with:
        args: |
          functions deploy unix-epoch-gmt \
            --source unix-epoch \
            --entry-point UnixEpoch \
            --runtime go113 \
            --trigger-http \
            --region europe-west1
